### ISSUE TITLE
Merge with official repository?

### ISSUE THREAD

**Issue by thorsten** [Maghin/docker-phpmyfaq#1]
Hi, I'm Thorsten, the official author of phpMyFAQ and I'm just stumbled upon your repo. Really looks cool, what do you think about merging your code into the official repository?

**Comment by Maghin** [comment]
Hi Thorsten, I'm glad you like it. I could try to fork the official project to add it.  There is also that fork https://github.com/joshisa/docker-phpmyfaq/commit/4ad3825c6001e41f13795d270079c59a5698d1ea that add PostgreSQL support, it could be a nice improvement.

**Comment by thorsten** [comment]
Sounds great, if you need help, get in touch!

**Comment by Maghin** [comment]
:cool: This is done !
